### ISSUE TITLE
Unexpected token caused after the comma when using multiple selectors on separate lines.

### ISSUE THREAD

**Issue by twoelevenjay** [krasimir/cssx#19]
This works:
```css
.r-nav-li:nth-child(1):before, .r-nav-li:nth-child(1):after {
	font-family: FontAwesome;
	display: inline-block;
	
}
```
This throws unexpected token error at `.r-nav-li:nth-child(1):after`:
```css
.r-nav-li:nth-child(1):before,
.r-nav-li:nth-child(1):after {
	font-family: FontAwesome;
	display: inline-block;
	
}
```
