### ISSUE TITLE
Parsing duplicate keys

### ISSUE THREAD

**Issue by AlastairTaft** [krasimir/cssx#9]
I'm having some trouble with the following.

```css
<style>
@font-face  {
    font-family: Dosis;
    font-weight: 400;
    src: url({{require('./fonts/Dosis-ExtraLight.ttf')}});,
  }
@font-face {
    font-family: Lato;
    font-weight: 300;
    src: url({{require('./fonts/Lato-Hairline.ttf')}};
  }
</style>
```
It then compiles to an object with just one `@font-face` key. Is there a way of handling this?
